version: '3'
services:
  mongodb:
    image: mongodb/mongodb-community-server:8.0-ubi8
    container_name: mongo-test
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: testuser
      MONGO_INITDB_ROOT_PASSWORD: testpass
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data: